// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class ReleaseNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 680
    let windowHeight: Int = 400

    // MARK: - Window Title
    let windowTitle: String = "{{ cookiecutter.product_name }}"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_release.png"
    let imageWidth: Int = 680
    let imageHeight: Int = 400
}
