// New file added for native_splash_screen integration (not part of the original Flet template).

// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class ProfileNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 128
    let windowHeight: Int = 128

    // MARK: - Window Title
    let windowTitle: String = "{{ cookiecutter.product_name }}"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_profile.png"
    let imageWidth: Int = 128
    let imageHeight: Int = 128
}
